# Dockerfile.grpc
FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Expose gRPC port
EXPOSE 50051

# Run gRPC server
CMD ["python", "backend_service/grpc_server.py"]